### ISSUE TITLE
[Feature] Fetch models

### ISSUE THREAD

**Issue by robsontenorio** [NoelDeMartin/cypress-laravel#3]
Some times you just want to pick some exiting random register or specifcs one that already exists.

```php
$country = Country::inRandomOrder()->first();   
$country = Country::find(38);
```

Would be nice some helpers like this.

```js
cy.random('App\\User')
cy.fetch('App\\User', 38)
```

**Comment by NoelDeMartin** [comment]
Thanks for opening the issue!

They make sense, but if I start adding those I'll end up replicating the entire Laravel API and I'm not sure if I want to have that maintenance burden.

I think what I can do is create an easy way to create custom commands by declaring them in the Cypress setup and implementing them with a php function. Maybe something like this:

Cypress setup:
```js
import { useCypressLaravel } from 'cypress-laravel';

useCypressLaravel({
    customCommands: ['random', 'fetch'],
});
```

Laravel setup (in a service provider):
```php
Cypress::customCommand('random', function ($model) {
    return $model::inRandomOrder()->first();  
});

Cypress::customCommand('fetch', function ($model, $id) {
    return $model::find($id);  
});

```

**Comment by robsontenorio** [comment]
Yes, I got your point. 

 Once I am comparing it with “laravel factory” feature approach , Maybe I am mixing things. 

If doesn’t make sense you can close it. Thanks ;)

**Comment by NoelDeMartin** [comment]
Ok, I'll leave it open until I add support for custom commands :).

**Comment by NoelDeMartin** [comment]
I've added support for custom commands in version 0.2.0.

As mentioned before, that should take care of any specific commands you may need in your project :). I've also added [an example](https://github.com/NoelDeMartin/laravel-cypress-sandbox/blob/master/cypress/integration/custom-commands.spec.js) in the sandbox project in case you want to check out the setup.
