### ISSUE TITLE
404 error {$laravelURL}/_cypress/setup

### ISSUE THREAD

**Issue by ryatkins** [NoelDeMartin/cypress-laravel#7]
Hi @NoelDeMartin,

When `useCypressLaravel();` is added to index.js, Cypress throws a 404 error on my url: `
{url: http://equotes.test/_cypress/setup, log: false}`

```
cy.request() failed on:

http://equotes.test/_cypress/setup

The response we received from your web server was:

  > 404: Not Found
```

I can overcome the Cypress error by overriding in my env via:
`CYPRESS_LARAVEL_URL=http://equotes.test npm run cypress`

but Laravel throws an error  that the env is incorrect.

PHP 7.4.12
Laravel v7.28.4 

**cypress/support/index.js**
```
import { useCypressLaravel } from 'cypress-laravel';

useCypressLaravel();
```

**cypress.json**  (I've tried with and without baseURL and env.laravelUrl
```
  {
        "baseUrl": "http://equotes.test",
        "env": {
            "laravelUrl": "http://equotes.test"
        },
        "viewportWidth": 1400,
        "viewportHeight": 660
      }
```

Thanks,
Ryan

**Comment by NoelDeMartin** [comment]
Hi there,

Can you show me the error that Laravel throws saying that env is incorrect? The config you shared looks good to me.

This looks like the companion laravel package is not installed, can you double check that this folder exists in your project: `vendor/noeldemartin/laravel-cypress`

**Comment by NoelDeMartin** [comment]
I'm closing this since it's gone stale and I can't reproduce it, feel free to open a new issue if you still have the error.
